2023-06-05 17:54:49.083328: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO:hpbandster:DISPATCHER: started the 'discover_worker' thread
INFO:hpbandster:DISPATCHER: started the 'job_runner' thread
INFO:hpbandster:DISPATCHER: Pyro daemon running on localhost:44011
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.25844
INFO:hpbandster:HBMASTER: adjusted queue size to (0, 1)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.25887
INFO:hpbandster:HBMASTER: adjusted queue size to (1, 2)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.25930
INFO:hpbandster:HBMASTER: adjusted queue size to (2, 3)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.25979
INFO:hpbandster:HBMASTER: adjusted queue size to (3, 4)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.26028
INFO:hpbandster:HBMASTER: adjusted queue size to (4, 5)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.26077
INFO:hpbandster:HBMASTER: adjusted queue size to (5, 6)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.26126
INFO:hpbandster:HBMASTER: adjusted queue size to (6, 7)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.26175
INFO:hpbandster:HBMASTER: adjusted queue size to (7, 8)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.26224
INFO:hpbandster:HBMASTER: adjusted queue size to (8, 9)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.26273
INFO:hpbandster:HBMASTER: adjusted queue size to (9, 10)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.26322
INFO:hpbandster:HBMASTER: adjusted queue size to (10, 11)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.26371
INFO:hpbandster:HBMASTER: adjusted queue size to (11, 12)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.26420
INFO:hpbandster:HBMASTER: adjusted queue size to (12, 13)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.26469
INFO:hpbandster:HBMASTER: adjusted queue size to (13, 14)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.26518
INFO:hpbandster:HBMASTER: adjusted queue size to (14, 15)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.26577
INFO:hpbandster:HBMASTER: adjusted queue size to (15, 16)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.26626
INFO:hpbandster:HBMASTER: adjusted queue size to (16, 17)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.26676
INFO:hpbandster:HBMASTER: adjusted queue size to (17, 18)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.26725
INFO:hpbandster:HBMASTER: adjusted queue size to (18, 19)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.26774
INFO:hpbandster:HBMASTER: adjusted queue size to (19, 20)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.26824
INFO:hpbandster:HBMASTER: adjusted queue size to (20, 21)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.26873
INFO:hpbandster:HBMASTER: adjusted queue size to (21, 22)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.26922
INFO:hpbandster:HBMASTER: adjusted queue size to (22, 23)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.26972
INFO:hpbandster:HBMASTER: adjusted queue size to (23, 24)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.27021
INFO:hpbandster:HBMASTER: adjusted queue size to (24, 25)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.27070
INFO:hpbandster:HBMASTER: adjusted queue size to (25, 26)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.27120
INFO:hpbandster:HBMASTER: adjusted queue size to (26, 27)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.27169
INFO:hpbandster:HBMASTER: adjusted queue size to (27, 28)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.27218
INFO:hpbandster:HBMASTER: adjusted queue size to (28, 29)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.27267
INFO:hpbandster:HBMASTER: adjusted queue size to (29, 30)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.27316
INFO:hpbandster:HBMASTER: adjusted queue size to (30, 31)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.27365
INFO:hpbandster:HBMASTER: adjusted queue size to (31, 32)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.27414
INFO:hpbandster:HBMASTER: adjusted queue size to (32, 33)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.27463
INFO:hpbandster:HBMASTER: adjusted queue size to (33, 34)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.27513
INFO:hpbandster:HBMASTER: adjusted queue size to (34, 35)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.27571
INFO:hpbandster:HBMASTER: adjusted queue size to (35, 36)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.27623
INFO:hpbandster:HBMASTER: adjusted queue size to (36, 37)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.27672
INFO:hpbandster:HBMASTER: adjusted queue size to (37, 38)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.27722
INFO:hpbandster:HBMASTER: adjusted queue size to (38, 39)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.27771
INFO:hpbandster:HBMASTER: adjusted queue size to (39, 40)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:HBMASTER: starting run at 1686013023.4732525
WARNING:hpbandster:job (10, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L1" (type MaxPooling1D).

Negative dimension size caused by subtracting 7 from 2 for '{{node MaxPooling1D__B3_L1/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 7, 1, 1], padding="VALID", strides=[1, 7, 1, 1]](MaxPooling1D__B3_L1/ExpandDims)' with input shapes: [?,2,1,128].

Call arguments received by layer "MaxPooling1D__B3_L1" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 128), dtype=float32)

WARNING:hpbandster:job (2, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L1" (type MaxPooling1D).

Negative dimension size caused by subtracting 8 from 1 for '{{node MaxPooling1D__B3_L1/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 8, 1, 1], padding="VALID", strides=[1, 8, 1, 1]](MaxPooling1D__B3_L1/ExpandDims)' with input shapes: [?,1,1,16].

Call arguments received by layer "MaxPooling1D__B3_L1" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 1, 16), dtype=float32)

WARNING:hpbandster:job (11, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L2" (type MaxPooling1D).

Negative dimension size caused by subtracting 5 from 4 for '{{node MaxPooling1D__B3_L2/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 5, 1, 1], padding="VALID", strides=[1, 5, 1, 1]](MaxPooling1D__B3_L2/ExpandDims)' with input shapes: [?,4,1,128].

Call arguments received by layer "MaxPooling1D__B3_L2" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 4, 128), dtype=float32)

WARNING:hpbandster:job (15, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L1" (type MaxPooling1D).

Negative dimension size caused by subtracting 8 from 1 for '{{node MaxPooling1D__B3_L1/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 8, 1, 1], padding="VALID", strides=[1, 8, 1, 1]](MaxPooling1D__B3_L1/ExpandDims)' with input shapes: [?,1,1,32].

Call arguments received by layer "MaxPooling1D__B3_L1" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 1, 32), dtype=float32)

WARNING:hpbandster:job (6, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L3" (type MaxPooling1D).

Negative dimension size caused by subtracting 7 from 2 for '{{node MaxPooling1D__B3_L3/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 7, 1, 1], padding="VALID", strides=[1, 7, 1, 1]](MaxPooling1D__B3_L3/ExpandDims)' with input shapes: [?,2,1,32].

Call arguments received by layer "MaxPooling1D__B3_L3" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 32), dtype=float32)

WARNING:hpbandster:job (14, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L2" (type MaxPooling1D).

Negative dimension size caused by subtracting 8 from 1 for '{{node MaxPooling1D__B3_L2/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 8, 1, 1], padding="VALID", strides=[1, 8, 1, 1]](MaxPooling1D__B3_L2/ExpandDims)' with input shapes: [?,1,1,64].

Call arguments received by layer "MaxPooling1D__B3_L2" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 1, 64), dtype=float32)

WARNING:hpbandster:job (0, 0, 2) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L4" (type MaxPooling1D).

Negative dimension size caused by subtracting 5 from 4 for '{{node MaxPooling1D__B3_L4/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 5, 1, 1], padding="VALID", strides=[1, 5, 1, 1]](MaxPooling1D__B3_L4/ExpandDims)' with input shapes: [?,4,1,128].

Call arguments received by layer "MaxPooling1D__B3_L4" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 4, 128), dtype=float32)

WARNING:hpbandster:job (4, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L3" (type MaxPooling1D).

Negative dimension size caused by subtracting 7 from 2 for '{{node MaxPooling1D__B3_L3/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 7, 1, 1], padding="VALID", strides=[1, 7, 1, 1]](MaxPooling1D__B3_L3/ExpandDims)' with input shapes: [?,2,1,32].

Call arguments received by layer "MaxPooling1D__B3_L3" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 32), dtype=float32)

WARNING:hpbandster:job (16, 0, 2) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L1" (type MaxPooling1D).

Negative dimension size caused by subtracting 7 from 2 for '{{node MaxPooling1D__B3_L1/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 7, 1, 1], padding="VALID", strides=[1, 7, 1, 1]](MaxPooling1D__B3_L1/ExpandDims)' with input shapes: [?,2,1,128].

Call arguments received by layer "MaxPooling1D__B3_L1" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 128), dtype=float32)

WARNING:hpbandster:job (4, 0, 2) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B4_L4" (type MaxPooling1D).

Negative dimension size caused by subtracting 4 from 1 for '{{node MaxPooling1D__B4_L4/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 4, 1, 1], padding="VALID", strides=[1, 4, 1, 1]](MaxPooling1D__B4_L4/ExpandDims)' with input shapes: [?,1,1,128].

Call arguments received by layer "MaxPooling1D__B4_L4" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 1, 128), dtype=float32)

WARNING:hpbandster:job (17, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L1" (type MaxPooling1D).

Negative dimension size caused by subtracting 5 from 4 for '{{node MaxPooling1D__B3_L1/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 5, 1, 1], padding="VALID", strides=[1, 5, 1, 1]](MaxPooling1D__B3_L1/ExpandDims)' with input shapes: [?,4,1,128].

Call arguments received by layer "MaxPooling1D__B3_L1" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 4, 128), dtype=float32)

WARNING:hpbandster:job (8, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L6" (type MaxPooling1D).

Negative dimension size caused by subtracting 6 from 2 for '{{node MaxPooling1D__B3_L6/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 6, 1, 1], padding="VALID", strides=[1, 6, 1, 1]](MaxPooling1D__B3_L6/ExpandDims)' with input shapes: [?,2,1,32].

Call arguments received by layer "MaxPooling1D__B3_L6" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 32), dtype=float32)

WARNING:hpbandster:job (19, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L1" (type MaxPooling1D).

Negative dimension size caused by subtracting 8 from 1 for '{{node MaxPooling1D__B3_L1/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 8, 1, 1], padding="VALID", strides=[1, 8, 1, 1]](MaxPooling1D__B3_L1/ExpandDims)' with input shapes: [?,1,1,128].

Call arguments received by layer "MaxPooling1D__B3_L1" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 1, 128), dtype=float32)

WARNING:hpbandster:job (18, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L4" (type MaxPooling1D).

Negative dimension size caused by subtracting 5 from 4 for '{{node MaxPooling1D__B3_L4/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 5, 1, 1], padding="VALID", strides=[1, 5, 1, 1]](MaxPooling1D__B3_L4/ExpandDims)' with input shapes: [?,4,1,64].

Call arguments received by layer "MaxPooling1D__B3_L4" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 4, 64), dtype=float32)

WARNING:hpbandster:job (19, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L6" (type MaxPooling1D).

Negative dimension size caused by subtracting 5 from 4 for '{{node MaxPooling1D__B3_L6/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 5, 1, 1], padding="VALID", strides=[1, 5, 1, 1]](MaxPooling1D__B3_L6/ExpandDims)' with input shapes: [?,4,1,16].

Call arguments received by layer "MaxPooling1D__B3_L6" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 4, 16), dtype=float32)

WARNING:hpbandster:job (20, 0, 2) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L3" (type MaxPooling1D).

Negative dimension size caused by subtracting 6 from 2 for '{{node MaxPooling1D__B3_L3/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 6, 1, 1], padding="VALID", strides=[1, 6, 1, 1]](MaxPooling1D__B3_L3/ExpandDims)' with input shapes: [?,2,1,32].

Call arguments received by layer "MaxPooling1D__B3_L3" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 32), dtype=float32)

WARNING:hpbandster:job (20, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L5" (type MaxPooling1D).

Negative dimension size caused by subtracting 8 from 1 for '{{node MaxPooling1D__B3_L5/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 8, 1, 1], padding="VALID", strides=[1, 8, 1, 1]](MaxPooling1D__B3_L5/ExpandDims)' with input shapes: [?,1,1,32].

Call arguments received by layer "MaxPooling1D__B3_L5" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 1, 32), dtype=float32)

WARNING:hpbandster:job (22, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L2" (type MaxPooling1D).

Negative dimension size caused by subtracting 7 from 2 for '{{node MaxPooling1D__B3_L2/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 7, 1, 1], padding="VALID", strides=[1, 7, 1, 1]](MaxPooling1D__B3_L2/ExpandDims)' with input shapes: [?,2,1,16].

Call arguments received by layer "MaxPooling1D__B3_L2" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 16), dtype=float32)

WARNING:hpbandster:job (22, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L5" (type MaxPooling1D).

Negative dimension size caused by subtracting 8 from 1 for '{{node MaxPooling1D__B3_L5/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 8, 1, 1], padding="VALID", strides=[1, 8, 1, 1]](MaxPooling1D__B3_L5/ExpandDims)' with input shapes: [?,1,1,64].

Call arguments received by layer "MaxPooling1D__B3_L5" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 1, 64), dtype=float32)

WARNING:hpbandster:job (23, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L6" (type MaxPooling1D).

Negative dimension size caused by subtracting 8 from 1 for '{{node MaxPooling1D__B3_L6/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 8, 1, 1], padding="VALID", strides=[1, 8, 1, 1]](MaxPooling1D__B3_L6/ExpandDims)' with input shapes: [?,1,1,32].

Call arguments received by layer "MaxPooling1D__B3_L6" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 1, 32), dtype=float32)

WARNING:hpbandster:job (24, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L4" (type MaxPooling1D).

Negative dimension size caused by subtracting 5 from 4 for '{{node MaxPooling1D__B3_L4/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 5, 1, 1], padding="VALID", strides=[1, 5, 1, 1]](MaxPooling1D__B3_L4/ExpandDims)' with input shapes: [?,4,1,32].

Call arguments received by layer "MaxPooling1D__B3_L4" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 4, 32), dtype=float32)

WARNING:hpbandster:job (24, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L2" (type MaxPooling1D).

Negative dimension size caused by subtracting 5 from 4 for '{{node MaxPooling1D__B3_L2/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 5, 1, 1], padding="VALID", strides=[1, 5, 1, 1]](MaxPooling1D__B3_L2/ExpandDims)' with input shapes: [?,4,1,32].

Call arguments received by layer "MaxPooling1D__B3_L2" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 4, 32), dtype=float32)

WARNING:hpbandster:job (26, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L5" (type MaxPooling1D).

Negative dimension size caused by subtracting 6 from 2 for '{{node MaxPooling1D__B3_L5/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 6, 1, 1], padding="VALID", strides=[1, 6, 1, 1]](MaxPooling1D__B3_L5/ExpandDims)' with input shapes: [?,2,1,64].

Call arguments received by layer "MaxPooling1D__B3_L5" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 64), dtype=float32)

WARNING:hpbandster:job (26, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L3" (type MaxPooling1D).

Negative dimension size caused by subtracting 7 from 2 for '{{node MaxPooling1D__B3_L3/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 7, 1, 1], padding="VALID", strides=[1, 7, 1, 1]](MaxPooling1D__B3_L3/ExpandDims)' with input shapes: [?,2,1,16].

Call arguments received by layer "MaxPooling1D__B3_L3" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 16), dtype=float32)

WARNING:hpbandster:job (28, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L2" (type MaxPooling1D).

Negative dimension size caused by subtracting 7 from 2 for '{{node MaxPooling1D__B3_L2/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 7, 1, 1], padding="VALID", strides=[1, 7, 1, 1]](MaxPooling1D__B3_L2/ExpandDims)' with input shapes: [?,2,1,16].

Call arguments received by layer "MaxPooling1D__B3_L2" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 16), dtype=float32)

WARNING:hpbandster:job (29, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B4_L1" (type MaxPooling1D).

Negative dimension size caused by subtracting 4 from 1 for '{{node MaxPooling1D__B4_L1/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 4, 1, 1], padding="VALID", strides=[1, 4, 1, 1]](MaxPooling1D__B4_L1/ExpandDims)' with input shapes: [?,1,1,128].

Call arguments received by layer "MaxPooling1D__B4_L1" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 1, 128), dtype=float32)

WARNING:hpbandster:job (30, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L1" (type MaxPooling1D).

Negative dimension size caused by subtracting 6 from 2 for '{{node MaxPooling1D__B3_L1/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 6, 1, 1], padding="VALID", strides=[1, 6, 1, 1]](MaxPooling1D__B3_L1/ExpandDims)' with input shapes: [?,2,1,128].

Call arguments received by layer "MaxPooling1D__B3_L1" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 128), dtype=float32)

WARNING:hpbandster:job (30, 0, 2) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L3" (type MaxPooling1D).

Negative dimension size caused by subtracting 5 from 4 for '{{node MaxPooling1D__B3_L3/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 5, 1, 1], padding="VALID", strides=[1, 5, 1, 1]](MaxPooling1D__B3_L3/ExpandDims)' with input shapes: [?,4,1,128].

Call arguments received by layer "MaxPooling1D__B3_L3" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 4, 128), dtype=float32)

WARNING:hpbandster:job (32, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L1" (type MaxPooling1D).

Negative dimension size caused by subtracting 8 from 1 for '{{node MaxPooling1D__B3_L1/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 8, 1, 1], padding="VALID", strides=[1, 8, 1, 1]](MaxPooling1D__B3_L1/ExpandDims)' with input shapes: [?,1,1,128].

Call arguments received by layer "MaxPooling1D__B3_L1" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 1, 128), dtype=float32)

WARNING:hpbandster:job (32, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L4" (type MaxPooling1D).

Negative dimension size caused by subtracting 5 from 4 for '{{node MaxPooling1D__B3_L4/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 5, 1, 1], padding="VALID", strides=[1, 5, 1, 1]](MaxPooling1D__B3_L4/ExpandDims)' with input shapes: [?,4,1,32].

Call arguments received by layer "MaxPooling1D__B3_L4" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 4, 32), dtype=float32)

WARNING:hpbandster:job (34, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L2" (type MaxPooling1D).

Negative dimension size caused by subtracting 5 from 4 for '{{node MaxPooling1D__B3_L2/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 5, 1, 1], padding="VALID", strides=[1, 5, 1, 1]](MaxPooling1D__B3_L2/ExpandDims)' with input shapes: [?,4,1,32].

Call arguments received by layer "MaxPooling1D__B3_L2" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 4, 32), dtype=float32)

WARNING:hpbandster:job (36, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L1" (type MaxPooling1D).

Negative dimension size caused by subtracting 8 from 1 for '{{node MaxPooling1D__B3_L1/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 8, 1, 1], padding="VALID", strides=[1, 8, 1, 1]](MaxPooling1D__B3_L1/ExpandDims)' with input shapes: [?,1,1,32].

Call arguments received by layer "MaxPooling1D__B3_L1" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 1, 32), dtype=float32)

WARNING:hpbandster:job (41, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L6" (type MaxPooling1D).

Negative dimension size caused by subtracting 6 from 2 for '{{node MaxPooling1D__B3_L6/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 6, 1, 1], padding="VALID", strides=[1, 6, 1, 1]](MaxPooling1D__B3_L6/ExpandDims)' with input shapes: [?,2,1,128].

Call arguments received by layer "MaxPooling1D__B3_L6" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 128), dtype=float32)

WARNING:hpbandster:job (41, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L4" (type MaxPooling1D).

Negative dimension size caused by subtracting 6 from 2 for '{{node MaxPooling1D__B3_L4/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 6, 1, 1], padding="VALID", strides=[1, 6, 1, 1]](MaxPooling1D__B3_L4/ExpandDims)' with input shapes: [?,2,1,128].

Call arguments received by layer "MaxPooling1D__B3_L4" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 128), dtype=float32)

WARNING:hpbandster:job (42, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L1" (type MaxPooling1D).

Negative dimension size caused by subtracting 7 from 2 for '{{node MaxPooling1D__B3_L1/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 7, 1, 1], padding="VALID", strides=[1, 7, 1, 1]](MaxPooling1D__B3_L1/ExpandDims)' with input shapes: [?,2,1,128].

Call arguments received by layer "MaxPooling1D__B3_L1" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 128), dtype=float32)

WARNING:hpbandster:job (42, 0, 2) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L4" (type MaxPooling1D).

Negative dimension size caused by subtracting 8 from 1 for '{{node MaxPooling1D__B3_L4/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 8, 1, 1], padding="VALID", strides=[1, 8, 1, 1]](MaxPooling1D__B3_L4/ExpandDims)' with input shapes: [?,1,1,128].

Call arguments received by layer "MaxPooling1D__B3_L4" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 1, 128), dtype=float32)

WARNING:hpbandster:job (43, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L5" (type MaxPooling1D).

Negative dimension size caused by subtracting 7 from 2 for '{{node MaxPooling1D__B3_L5/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 7, 1, 1], padding="VALID", strides=[1, 7, 1, 1]](MaxPooling1D__B3_L5/ExpandDims)' with input shapes: [?,2,1,16].

Call arguments received by layer "MaxPooling1D__B3_L5" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 16), dtype=float32)

WARNING:hpbandster:job (44, 0, 2) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L5" (type MaxPooling1D).

Negative dimension size caused by subtracting 7 from 2 for '{{node MaxPooling1D__B3_L5/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 7, 1, 1], padding="VALID", strides=[1, 7, 1, 1]](MaxPooling1D__B3_L5/ExpandDims)' with input shapes: [?,2,1,64].

Call arguments received by layer "MaxPooling1D__B3_L5" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 64), dtype=float32)

WARNING:hpbandster:job (46, 0, 2) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L2" (type MaxPooling1D).

Negative dimension size caused by subtracting 6 from 2 for '{{node MaxPooling1D__B3_L2/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 6, 1, 1], padding="VALID", strides=[1, 6, 1, 1]](MaxPooling1D__B3_L2/ExpandDims)' with input shapes: [?,2,1,16].

Call arguments received by layer "MaxPooling1D__B3_L2" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 16), dtype=float32)

WARNING:hpbandster:job (48, 0, 2) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L2" (type MaxPooling1D).

Negative dimension size caused by subtracting 8 from 1 for '{{node MaxPooling1D__B3_L2/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 8, 1, 1], padding="VALID", strides=[1, 8, 1, 1]](MaxPooling1D__B3_L2/ExpandDims)' with input shapes: [?,1,1,32].

Call arguments received by layer "MaxPooling1D__B3_L2" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 1, 32), dtype=float32)

WARNING:hpbandster:job (49, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L2" (type MaxPooling1D).

Negative dimension size caused by subtracting 5 from 4 for '{{node MaxPooling1D__B3_L2/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 5, 1, 1], padding="VALID", strides=[1, 5, 1, 1]](MaxPooling1D__B3_L2/ExpandDims)' with input shapes: [?,4,1,128].

Call arguments received by layer "MaxPooling1D__B3_L2" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 4, 128), dtype=float32)

WARNING:hpbandster:job (50, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L2" (type MaxPooling1D).

Negative dimension size caused by subtracting 6 from 2 for '{{node MaxPooling1D__B3_L2/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 6, 1, 1], padding="VALID", strides=[1, 6, 1, 1]](MaxPooling1D__B3_L2/ExpandDims)' with input shapes: [?,2,1,32].

Call arguments received by layer "MaxPooling1D__B3_L2" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 32), dtype=float32)

WARNING:hpbandster:job (56, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L1" (type MaxPooling1D).

Negative dimension size caused by subtracting 5 from 4 for '{{node MaxPooling1D__B3_L1/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 5, 1, 1], padding="VALID", strides=[1, 5, 1, 1]](MaxPooling1D__B3_L1/ExpandDims)' with input shapes: [?,4,1,64].

Call arguments received by layer "MaxPooling1D__B3_L1" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 4, 64), dtype=float32)

INFO:hpbandster:DISPATCHER: Dispatcher shutting down
INFO:hpbandster:DISPATCHER: shut down complete
