2023-06-02 16:34:08.379024: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO:hpbandster:DISPATCHER: started the 'discover_worker' thread
INFO:hpbandster:DISPATCHER: started the 'job_runner' thread
INFO:hpbandster:DISPATCHER: Pyro daemon running on localhost:43759
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.32946
INFO:hpbandster:HBMASTER: adjusted queue size to (0, 1)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.32994
INFO:hpbandster:HBMASTER: adjusted queue size to (1, 2)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.33036
INFO:hpbandster:HBMASTER: adjusted queue size to (2, 3)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.33086
INFO:hpbandster:HBMASTER: adjusted queue size to (3, 4)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.33135
INFO:hpbandster:HBMASTER: adjusted queue size to (4, 5)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.33184
INFO:hpbandster:HBMASTER: adjusted queue size to (5, 6)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.33233
INFO:hpbandster:HBMASTER: adjusted queue size to (6, 7)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.33282
INFO:hpbandster:HBMASTER: adjusted queue size to (7, 8)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.33331
INFO:hpbandster:HBMASTER: adjusted queue size to (8, 9)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.33380
INFO:hpbandster:HBMASTER: adjusted queue size to (9, 10)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.33429
INFO:hpbandster:HBMASTER: adjusted queue size to (10, 11)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.33480
INFO:hpbandster:HBMASTER: adjusted queue size to (11, 12)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.33529
INFO:hpbandster:HBMASTER: adjusted queue size to (12, 13)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.33578
INFO:hpbandster:HBMASTER: adjusted queue size to (13, 14)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.33627
INFO:hpbandster:HBMASTER: adjusted queue size to (14, 15)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.33677
INFO:hpbandster:HBMASTER: adjusted queue size to (15, 16)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.33726
INFO:hpbandster:HBMASTER: adjusted queue size to (16, 17)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.33775
INFO:hpbandster:HBMASTER: adjusted queue size to (17, 18)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.33824
INFO:hpbandster:HBMASTER: adjusted queue size to (18, 19)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.33873
INFO:hpbandster:HBMASTER: adjusted queue size to (19, 20)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.33922
INFO:hpbandster:HBMASTER: adjusted queue size to (20, 21)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.33981
INFO:hpbandster:HBMASTER: adjusted queue size to (21, 22)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.34030
INFO:hpbandster:HBMASTER: adjusted queue size to (22, 23)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.34079
INFO:hpbandster:HBMASTER: adjusted queue size to (23, 24)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.34203
INFO:hpbandster:HBMASTER: adjusted queue size to (24, 25)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.34252
INFO:hpbandster:HBMASTER: adjusted queue size to (25, 26)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.34303
INFO:hpbandster:HBMASTER: adjusted queue size to (26, 27)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.34353
INFO:hpbandster:HBMASTER: adjusted queue size to (27, 28)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.34402
INFO:hpbandster:HBMASTER: adjusted queue size to (28, 29)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.34452
INFO:hpbandster:HBMASTER: adjusted queue size to (29, 30)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.34502
INFO:hpbandster:HBMASTER: adjusted queue size to (30, 31)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.34551
INFO:hpbandster:HBMASTER: adjusted queue size to (31, 32)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.34600
INFO:hpbandster:HBMASTER: adjusted queue size to (32, 33)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.34649
INFO:hpbandster:HBMASTER: adjusted queue size to (33, 34)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.34698
INFO:hpbandster:HBMASTER: adjusted queue size to (34, 35)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.34751
INFO:hpbandster:HBMASTER: adjusted queue size to (35, 36)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.34800
INFO:hpbandster:HBMASTER: adjusted queue size to (36, 37)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.34850
INFO:hpbandster:HBMASTER: adjusted queue size to (37, 38)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.34899
INFO:hpbandster:HBMASTER: adjusted queue size to (38, 39)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_example3.worker.tijuca.ndc.nasa.gov.34948
INFO:hpbandster:HBMASTER: adjusted queue size to (39, 40)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:HBMASTER: starting run at 1685748983.4480371
WARNING:hpbandster:job (5, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B4_L1" (type MaxPooling1D).

Negative dimension size caused by subtracting 4 from 1 for '{{node MaxPooling1D__B4_L1/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 4, 1, 1], padding="VALID", strides=[1, 4, 1, 1]](MaxPooling1D__B4_L1/ExpandDims)' with input shapes: [?,1,1,64].

Call arguments received by layer "MaxPooling1D__B4_L1" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 1, 64), dtype=float32)

WARNING:hpbandster:job (10, 0, 2) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L1" (type MaxPooling1D).

Negative dimension size caused by subtracting 8 from 1 for '{{node MaxPooling1D__B3_L1/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 8, 1, 1], padding="VALID", strides=[1, 8, 1, 1]](MaxPooling1D__B3_L1/ExpandDims)' with input shapes: [?,1,1,32].

Call arguments received by layer "MaxPooling1D__B3_L1" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 1, 32), dtype=float32)

WARNING:hpbandster:job (12, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B4_L1" (type MaxPooling1D).

Negative dimension size caused by subtracting 4 from 1 for '{{node MaxPooling1D__B4_L1/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 4, 1, 1], padding="VALID", strides=[1, 4, 1, 1]](MaxPooling1D__B4_L1/ExpandDims)' with input shapes: [?,1,1,128].

Call arguments received by layer "MaxPooling1D__B4_L1" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 1, 128), dtype=float32)

WARNING:hpbandster:job (3, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L3" (type MaxPooling1D).

Negative dimension size caused by subtracting 7 from 2 for '{{node MaxPooling1D__B3_L3/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 7, 1, 1], padding="VALID", strides=[1, 7, 1, 1]](MaxPooling1D__B3_L3/ExpandDims)' with input shapes: [?,2,1,64].

Call arguments received by layer "MaxPooling1D__B3_L3" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 64), dtype=float32)

WARNING:hpbandster:job (14, 0, 2) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L2" (type MaxPooling1D).

Negative dimension size caused by subtracting 6 from 2 for '{{node MaxPooling1D__B3_L2/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 6, 1, 1], padding="VALID", strides=[1, 6, 1, 1]](MaxPooling1D__B3_L2/ExpandDims)' with input shapes: [?,2,1,32].

Call arguments received by layer "MaxPooling1D__B3_L2" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 32), dtype=float32)

WARNING:hpbandster:job (1, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L2" (type MaxPooling1D).

Negative dimension size caused by subtracting 6 from 2 for '{{node MaxPooling1D__B3_L2/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 6, 1, 1], padding="VALID", strides=[1, 6, 1, 1]](MaxPooling1D__B3_L2/ExpandDims)' with input shapes: [?,2,1,32].

Call arguments received by layer "MaxPooling1D__B3_L2" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 32), dtype=float32)

WARNING:hpbandster:job (14, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L3" (type MaxPooling1D).

Negative dimension size caused by subtracting 6 from 2 for '{{node MaxPooling1D__B3_L3/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 6, 1, 1], padding="VALID", strides=[1, 6, 1, 1]](MaxPooling1D__B3_L3/ExpandDims)' with input shapes: [?,2,1,64].

Call arguments received by layer "MaxPooling1D__B3_L3" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 64), dtype=float32)

WARNING:hpbandster:job (0, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L4" (type MaxPooling1D).

Negative dimension size caused by subtracting 6 from 2 for '{{node MaxPooling1D__B3_L4/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 6, 1, 1], padding="VALID", strides=[1, 6, 1, 1]](MaxPooling1D__B3_L4/ExpandDims)' with input shapes: [?,2,1,32].

Call arguments received by layer "MaxPooling1D__B3_L4" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 32), dtype=float32)

WARNING:hpbandster:job (2, 0, 2) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L4" (type MaxPooling1D).

Negative dimension size caused by subtracting 7 from 2 for '{{node MaxPooling1D__B3_L4/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 7, 1, 1], padding="VALID", strides=[1, 7, 1, 1]](MaxPooling1D__B3_L4/ExpandDims)' with input shapes: [?,2,1,32].

Call arguments received by layer "MaxPooling1D__B3_L4" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 32), dtype=float32)

WARNING:hpbandster:job (10, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L3" (type MaxPooling1D).

Negative dimension size caused by subtracting 6 from 2 for '{{node MaxPooling1D__B3_L3/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 6, 1, 1], padding="VALID", strides=[1, 6, 1, 1]](MaxPooling1D__B3_L3/ExpandDims)' with input shapes: [?,2,1,32].

Call arguments received by layer "MaxPooling1D__B3_L3" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 32), dtype=float32)

WARNING:hpbandster:job (13, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L2" (type MaxPooling1D).

Negative dimension size caused by subtracting 8 from 1 for '{{node MaxPooling1D__B3_L2/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 8, 1, 1], padding="VALID", strides=[1, 8, 1, 1]](MaxPooling1D__B3_L2/ExpandDims)' with input shapes: [?,1,1,16].

Call arguments received by layer "MaxPooling1D__B3_L2" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 1, 16), dtype=float32)

WARNING:hpbandster:job (5, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L3" (type MaxPooling1D).

Negative dimension size caused by subtracting 8 from 1 for '{{node MaxPooling1D__B3_L3/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 8, 1, 1], padding="VALID", strides=[1, 8, 1, 1]](MaxPooling1D__B3_L3/ExpandDims)' with input shapes: [?,1,1,16].

Call arguments received by layer "MaxPooling1D__B3_L3" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 1, 16), dtype=float32)

WARNING:hpbandster:job (12, 0, 2) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L6" (type MaxPooling1D).

Negative dimension size caused by subtracting 7 from 2 for '{{node MaxPooling1D__B3_L6/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 7, 1, 1], padding="VALID", strides=[1, 7, 1, 1]](MaxPooling1D__B3_L6/ExpandDims)' with input shapes: [?,2,1,16].

Call arguments received by layer "MaxPooling1D__B3_L6" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 16), dtype=float32)

WARNING:hpbandster:job (12, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L6" (type MaxPooling1D).

Negative dimension size caused by subtracting 7 from 2 for '{{node MaxPooling1D__B3_L6/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 7, 1, 1], padding="VALID", strides=[1, 7, 1, 1]](MaxPooling1D__B3_L6/ExpandDims)' with input shapes: [?,2,1,128].

Call arguments received by layer "MaxPooling1D__B3_L6" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 128), dtype=float32)

WARNING:hpbandster:job (17, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L3" (type MaxPooling1D).

Negative dimension size caused by subtracting 7 from 2 for '{{node MaxPooling1D__B3_L3/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 7, 1, 1], padding="VALID", strides=[1, 7, 1, 1]](MaxPooling1D__B3_L3/ExpandDims)' with input shapes: [?,2,1,128].

Call arguments received by layer "MaxPooling1D__B3_L3" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 128), dtype=float32)

WARNING:hpbandster:job (10, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L5" (type MaxPooling1D).

Negative dimension size caused by subtracting 5 from 4 for '{{node MaxPooling1D__B3_L5/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 5, 1, 1], padding="VALID", strides=[1, 5, 1, 1]](MaxPooling1D__B3_L5/ExpandDims)' with input shapes: [?,4,1,64].

Call arguments received by layer "MaxPooling1D__B3_L5" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 4, 64), dtype=float32)

WARNING:hpbandster:job (11, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B4_L4" (type MaxPooling1D).

Negative dimension size caused by subtracting 4 from 1 for '{{node MaxPooling1D__B4_L4/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 4, 1, 1], padding="VALID", strides=[1, 4, 1, 1]](MaxPooling1D__B4_L4/ExpandDims)' with input shapes: [?,1,1,128].

Call arguments received by layer "MaxPooling1D__B4_L4" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 1, 128), dtype=float32)

WARNING:hpbandster:job (19, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L3" (type MaxPooling1D).

Negative dimension size caused by subtracting 8 from 1 for '{{node MaxPooling1D__B3_L3/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 8, 1, 1], padding="VALID", strides=[1, 8, 1, 1]](MaxPooling1D__B3_L3/ExpandDims)' with input shapes: [?,1,1,16].

Call arguments received by layer "MaxPooling1D__B3_L3" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 1, 16), dtype=float32)

WARNING:hpbandster:job (20, 0, 2) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L3" (type MaxPooling1D).

Negative dimension size caused by subtracting 7 from 2 for '{{node MaxPooling1D__B3_L3/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 7, 1, 1], padding="VALID", strides=[1, 7, 1, 1]](MaxPooling1D__B3_L3/ExpandDims)' with input shapes: [?,2,1,128].

Call arguments received by layer "MaxPooling1D__B3_L3" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 128), dtype=float32)

WARNING:hpbandster:job (21, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L2" (type MaxPooling1D).

Negative dimension size caused by subtracting 8 from 1 for '{{node MaxPooling1D__B3_L2/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 8, 1, 1], padding="VALID", strides=[1, 8, 1, 1]](MaxPooling1D__B3_L2/ExpandDims)' with input shapes: [?,1,1,32].

Call arguments received by layer "MaxPooling1D__B3_L2" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 1, 32), dtype=float32)

WARNING:hpbandster:job (23, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L1" (type MaxPooling1D).

Negative dimension size caused by subtracting 5 from 4 for '{{node MaxPooling1D__B3_L1/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 5, 1, 1], padding="VALID", strides=[1, 5, 1, 1]](MaxPooling1D__B3_L1/ExpandDims)' with input shapes: [?,4,1,16].

Call arguments received by layer "MaxPooling1D__B3_L1" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 4, 16), dtype=float32)

WARNING:hpbandster:job (24, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L4" (type MaxPooling1D).

Negative dimension size caused by subtracting 8 from 1 for '{{node MaxPooling1D__B3_L4/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 8, 1, 1], padding="VALID", strides=[1, 8, 1, 1]](MaxPooling1D__B3_L4/ExpandDims)' with input shapes: [?,1,1,64].

Call arguments received by layer "MaxPooling1D__B3_L4" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 1, 64), dtype=float32)

WARNING:hpbandster:job (26, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L3" (type MaxPooling1D).

Negative dimension size caused by subtracting 5 from 4 for '{{node MaxPooling1D__B3_L3/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 5, 1, 1], padding="VALID", strides=[1, 5, 1, 1]](MaxPooling1D__B3_L3/ExpandDims)' with input shapes: [?,4,1,64].

Call arguments received by layer "MaxPooling1D__B3_L3" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 4, 64), dtype=float32)

WARNING:hpbandster:job (27, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L3" (type MaxPooling1D).

Negative dimension size caused by subtracting 5 from 4 for '{{node MaxPooling1D__B3_L3/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 5, 1, 1], padding="VALID", strides=[1, 5, 1, 1]](MaxPooling1D__B3_L3/ExpandDims)' with input shapes: [?,4,1,32].

Call arguments received by layer "MaxPooling1D__B3_L3" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 4, 32), dtype=float32)

WARNING:hpbandster:job (30, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L5" (type MaxPooling1D).

Negative dimension size caused by subtracting 7 from 2 for '{{node MaxPooling1D__B3_L5/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 7, 1, 1], padding="VALID", strides=[1, 7, 1, 1]](MaxPooling1D__B3_L5/ExpandDims)' with input shapes: [?,2,1,32].

Call arguments received by layer "MaxPooling1D__B3_L5" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 32), dtype=float32)

WARNING:hpbandster:job (34, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L1" (type MaxPooling1D).

Negative dimension size caused by subtracting 6 from 2 for '{{node MaxPooling1D__B3_L1/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 6, 1, 1], padding="VALID", strides=[1, 6, 1, 1]](MaxPooling1D__B3_L1/ExpandDims)' with input shapes: [?,2,1,128].

Call arguments received by layer "MaxPooling1D__B3_L1" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 128), dtype=float32)

WARNING:hpbandster:job (38, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py", line 211, in compute
    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py", line 6493, in pool2d
    x = tf.compat.v1.nn.max_pool(
ValueError: Exception encountered when calling layer "MaxPooling1D__B3_L2" (type MaxPooling1D).

Negative dimension size caused by subtracting 6 from 2 for '{{node MaxPooling1D__B3_L2/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", explicit_paddings=[], ksize=[1, 6, 1, 1], padding="VALID", strides=[1, 6, 1, 1]](MaxPooling1D__B3_L2/ExpandDims)' with input shapes: [?,2,1,64].

Call arguments received by layer "MaxPooling1D__B3_L2" (type MaxPooling1D):
  • inputs=tf.Tensor(shape=(None, 2, 64), dtype=float32)

