[[8, 0, 2], 16.666666666666664, {"submitted": 1686012694.1276796, "started": 1686012694.1294882, "finished": 1686012694.3033612}, null, "Traceback (most recent call last):\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py\", line 211, in compute\n    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py\", line 6493, in pool2d\n    x = tf.compat.v1.nn.max_pool(\nValueError: Exception encountered when calling layer \"MaxPooling1D__B3_L1\" (type MaxPooling1D).\n\nNegative dimension size caused by subtracting 6 from 2 for '{{node MaxPooling1D__B3_L1/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 6, 1, 1], padding=\"VALID\", strides=[1, 6, 1, 1]](MaxPooling1D__B3_L1/ExpandDims)' with input shapes: [?,2,1,32].\n\nCall arguments received by layer \"MaxPooling1D__B3_L1\" (type MaxPooling1D):\n  \u2022 inputs=tf.Tensor(shape=(None, 2, 32), dtype=float32)\n"]
[[1, 0, 1], 50.0, {"submitted": 1686012694.0983064, "started": 1686012694.099323, "finished": 1686012694.3846147}, null, "Traceback (most recent call last):\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py\", line 211, in compute\n    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py\", line 6493, in pool2d\n    x = tf.compat.v1.nn.max_pool(\nValueError: Exception encountered when calling layer \"MaxPooling1D__B3_L3\" (type MaxPooling1D).\n\nNegative dimension size caused by subtracting 5 from 4 for '{{node MaxPooling1D__B3_L3/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 5, 1, 1], padding=\"VALID\", strides=[1, 5, 1, 1]](MaxPooling1D__B3_L3/ExpandDims)' with input shapes: [?,4,1,64].\n\nCall arguments received by layer \"MaxPooling1D__B3_L3\" (type MaxPooling1D):\n  \u2022 inputs=tf.Tensor(shape=(None, 4, 64), dtype=float32)\n"]
[[4, 0, 0], 16.666666666666664, {"submitted": 1686012694.109056, "started": 1686012694.110011, "finished": 1686012694.4254565}, null, "Traceback (most recent call last):\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py\", line 211, in compute\n    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py\", line 6493, in pool2d\n    x = tf.compat.v1.nn.max_pool(\nValueError: Exception encountered when calling layer \"MaxPooling1D__B3_L6\" (type MaxPooling1D).\n\nNegative dimension size caused by subtracting 8 from 1 for '{{node MaxPooling1D__B3_L6/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 8, 1, 1], padding=\"VALID\", strides=[1, 8, 1, 1]](MaxPooling1D__B3_L6/ExpandDims)' with input shapes: [?,1,1,128].\n\nCall arguments received by layer \"MaxPooling1D__B3_L6\" (type MaxPooling1D):\n  \u2022 inputs=tf.Tensor(shape=(None, 1, 128), dtype=float32)\n"]
[[14, 0, 2], 16.666666666666664, {"submitted": 1686012694.160624, "started": 1686012694.1653428, "finished": 1686012694.4809313}, null, "Traceback (most recent call last):\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py\", line 211, in compute\n    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py\", line 6493, in pool2d\n    x = tf.compat.v1.nn.max_pool(\nValueError: Exception encountered when calling layer \"MaxPooling1D__B3_L5\" (type MaxPooling1D).\n\nNegative dimension size caused by subtracting 5 from 4 for '{{node MaxPooling1D__B3_L5/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 5, 1, 1], padding=\"VALID\", strides=[1, 5, 1, 1]](MaxPooling1D__B3_L5/ExpandDims)' with input shapes: [?,4,1,64].\n\nCall arguments received by layer \"MaxPooling1D__B3_L5\" (type MaxPooling1D):\n  \u2022 inputs=tf.Tensor(shape=(None, 4, 64), dtype=float32)\n"]
[[15, 0, 0], 50.0, {"submitted": 1686012694.1624074, "started": 1686012694.1656215, "finished": 1686012694.4927473}, null, "Traceback (most recent call last):\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py\", line 211, in compute\n    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py\", line 6493, in pool2d\n    x = tf.compat.v1.nn.max_pool(\nValueError: Exception encountered when calling layer \"MaxPooling1D__B3_L3\" (type MaxPooling1D).\n\nNegative dimension size caused by subtracting 5 from 4 for '{{node MaxPooling1D__B3_L3/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 5, 1, 1], padding=\"VALID\", strides=[1, 5, 1, 1]](MaxPooling1D__B3_L3/ExpandDims)' with input shapes: [?,4,1,16].\n\nCall arguments received by layer \"MaxPooling1D__B3_L3\" (type MaxPooling1D):\n  \u2022 inputs=tf.Tensor(shape=(None, 4, 16), dtype=float32)\n"]
[[10, 0, 1], 16.666666666666664, {"submitted": 1686012694.135561, "started": 1686012694.1360674, "finished": 1686012694.5019674}, null, "Traceback (most recent call last):\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py\", line 211, in compute\n    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py\", line 6493, in pool2d\n    x = tf.compat.v1.nn.max_pool(\nValueError: Exception encountered when calling layer \"MaxPooling1D__B3_L5\" (type MaxPooling1D).\n\nNegative dimension size caused by subtracting 7 from 2 for '{{node MaxPooling1D__B3_L5/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 7, 1, 1], padding=\"VALID\", strides=[1, 7, 1, 1]](MaxPooling1D__B3_L5/ExpandDims)' with input shapes: [?,2,1,64].\n\nCall arguments received by layer \"MaxPooling1D__B3_L5\" (type MaxPooling1D):\n  \u2022 inputs=tf.Tensor(shape=(None, 2, 64), dtype=float32)\n"]
[[5, 0, 1], 50.0, {"submitted": 1686012694.1156497, "started": 1686012694.116708, "finished": 1686012694.5161262}, null, "Traceback (most recent call last):\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py\", line 211, in compute\n    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py\", line 6493, in pool2d\n    x = tf.compat.v1.nn.max_pool(\nValueError: Exception encountered when calling layer \"MaxPooling1D__B3_L6\" (type MaxPooling1D).\n\nNegative dimension size caused by subtracting 6 from 2 for '{{node MaxPooling1D__B3_L6/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 6, 1, 1], padding=\"VALID\", strides=[1, 6, 1, 1]](MaxPooling1D__B3_L6/ExpandDims)' with input shapes: [?,2,1,64].\n\nCall arguments received by layer \"MaxPooling1D__B3_L6\" (type MaxPooling1D):\n  \u2022 inputs=tf.Tensor(shape=(None, 2, 64), dtype=float32)\n"]
[[11, 0, 1], 50.0, {"submitted": 1686012694.1419458, "started": 1686012694.1425161, "finished": 1686012694.532009}, null, "Traceback (most recent call last):\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py\", line 211, in compute\n    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py\", line 6493, in pool2d\n    x = tf.compat.v1.nn.max_pool(\nValueError: Exception encountered when calling layer \"MaxPooling1D__B3_L6\" (type MaxPooling1D).\n\nNegative dimension size caused by subtracting 7 from 2 for '{{node MaxPooling1D__B3_L6/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 7, 1, 1], padding=\"VALID\", strides=[1, 7, 1, 1]](MaxPooling1D__B3_L6/ExpandDims)' with input shapes: [?,2,1,16].\n\nCall arguments received by layer \"MaxPooling1D__B3_L6\" (type MaxPooling1D):\n  \u2022 inputs=tf.Tensor(shape=(None, 2, 16), dtype=float32)\n"]
[[16, 0, 1], 16.666666666666664, {"submitted": 1686012694.3873475, "started": 1686012694.387578, "finished": 1686012694.5349255}, null, "Traceback (most recent call last):\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py\", line 211, in compute\n    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py\", line 6493, in pool2d\n    x = tf.compat.v1.nn.max_pool(\nValueError: Exception encountered when calling layer \"MaxPooling1D__B3_L3\" (type MaxPooling1D).\n\nNegative dimension size caused by subtracting 5 from 4 for '{{node MaxPooling1D__B3_L3/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 5, 1, 1], padding=\"VALID\", strides=[1, 5, 1, 1]](MaxPooling1D__B3_L3/ExpandDims)' with input shapes: [?,4,1,16].\n\nCall arguments received by layer \"MaxPooling1D__B3_L3\" (type MaxPooling1D):\n  \u2022 inputs=tf.Tensor(shape=(None, 4, 16), dtype=float32)\n"]
[[14, 0, 1], 16.666666666666664, {"submitted": 1686012694.1588783, "started": 1686012694.1650703, "finished": 1686012694.5422497}, null, "Traceback (most recent call last):\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py\", line 211, in compute\n    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py\", line 6493, in pool2d\n    x = tf.compat.v1.nn.max_pool(\nValueError: Exception encountered when calling layer \"MaxPooling1D__B3_L5\" (type MaxPooling1D).\n\nNegative dimension size caused by subtracting 6 from 2 for '{{node MaxPooling1D__B3_L5/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 6, 1, 1], padding=\"VALID\", strides=[1, 6, 1, 1]](MaxPooling1D__B3_L5/ExpandDims)' with input shapes: [?,2,1,128].\n\nCall arguments received by layer \"MaxPooling1D__B3_L5\" (type MaxPooling1D):\n  \u2022 inputs=tf.Tensor(shape=(None, 2, 128), dtype=float32)\n"]
[[10, 0, 0], 16.666666666666664, {"submitted": 1686012694.1341264, "started": 1686012694.1344337, "finished": 1686012694.5499105}, null, "Traceback (most recent call last):\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py\", line 211, in compute\n    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py\", line 6493, in pool2d\n    x = tf.compat.v1.nn.max_pool(\nValueError: Exception encountered when calling layer \"MaxPooling1D__B3_L6\" (type MaxPooling1D).\n\nNegative dimension size caused by subtracting 5 from 4 for '{{node MaxPooling1D__B3_L6/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 5, 1, 1], padding=\"VALID\", strides=[1, 5, 1, 1]](MaxPooling1D__B3_L6/ExpandDims)' with input shapes: [?,4,1,128].\n\nCall arguments received by layer \"MaxPooling1D__B3_L6\" (type MaxPooling1D):\n  \u2022 inputs=tf.Tensor(shape=(None, 4, 128), dtype=float32)\n"]
[[18, 0, 0], 16.666666666666664, {"submitted": 1686012694.505095, "started": 1686012694.5052052, "finished": 1686012694.678829}, null, "Traceback (most recent call last):\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py\", line 211, in compute\n    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py\", line 6493, in pool2d\n    x = tf.compat.v1.nn.max_pool(\nValueError: Exception encountered when calling layer \"MaxPooling1D__B3_L3\" (type MaxPooling1D).\n\nNegative dimension size caused by subtracting 7 from 2 for '{{node MaxPooling1D__B3_L3/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 7, 1, 1], padding=\"VALID\", strides=[1, 7, 1, 1]](MaxPooling1D__B3_L3/ExpandDims)' with input shapes: [?,2,1,32].\n\nCall arguments received by layer \"MaxPooling1D__B3_L3\" (type MaxPooling1D):\n  \u2022 inputs=tf.Tensor(shape=(None, 2, 32), dtype=float32)\n"]
[[19, 0, 0], 50.0, {"submitted": 1686012694.5432847, "started": 1686012694.543847, "finished": 1686012694.7536492}, null, "Traceback (most recent call last):\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py\", line 211, in compute\n    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py\", line 6493, in pool2d\n    x = tf.compat.v1.nn.max_pool(\nValueError: Exception encountered when calling layer \"MaxPooling1D__B3_L5\" (type MaxPooling1D).\n\nNegative dimension size caused by subtracting 7 from 2 for '{{node MaxPooling1D__B3_L5/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 7, 1, 1], padding=\"VALID\", strides=[1, 7, 1, 1]](MaxPooling1D__B3_L5/ExpandDims)' with input shapes: [?,2,1,128].\n\nCall arguments received by layer \"MaxPooling1D__B3_L5\" (type MaxPooling1D):\n  \u2022 inputs=tf.Tensor(shape=(None, 2, 128), dtype=float32)\n"]
[[20, 0, 2], 16.666666666666664, {"submitted": 1686012694.757473, "started": 1686012694.7576084, "finished": 1686012694.9485543}, null, "Traceback (most recent call last):\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py\", line 211, in compute\n    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py\", line 6493, in pool2d\n    x = tf.compat.v1.nn.max_pool(\nValueError: Exception encountered when calling layer \"MaxPooling1D__B3_L5\" (type MaxPooling1D).\n\nNegative dimension size caused by subtracting 7 from 2 for '{{node MaxPooling1D__B3_L5/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 7, 1, 1], padding=\"VALID\", strides=[1, 7, 1, 1]](MaxPooling1D__B3_L5/ExpandDims)' with input shapes: [?,2,1,64].\n\nCall arguments received by layer \"MaxPooling1D__B3_L5\" (type MaxPooling1D):\n  \u2022 inputs=tf.Tensor(shape=(None, 2, 64), dtype=float32)\n"]
[[21, 0, 0], 50.0, {"submitted": 1686012694.9513621, "started": 1686012694.9515123, "finished": 1686012695.2770407}, null, "Traceback (most recent call last):\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/hpbandster/core/worker.py\", line 206, in start_computation\n    result = {'result': self.compute(*args, config_id=id, **kwargs),\n  File \"/data2/ehsan_storage/telescopeML/core_codes/bohb_tuning/cnn_bohb_tuning7.py\", line 211, in compute\n    model = MaxPooling1D(pool_size=(Conv__MaxPooling1D),\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/egharibn/anaconda3/envs/bohb/lib/python3.9/site-packages/keras/backend.py\", line 6493, in pool2d\n    x = tf.compat.v1.nn.max_pool(\nValueError: Exception encountered when calling layer \"MaxPooling1D__B3_L6\" (type MaxPooling1D).\n\nNegative dimension size caused by subtracting 5 from 4 for '{{node MaxPooling1D__B3_L6/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 5, 1, 1], padding=\"VALID\", strides=[1, 5, 1, 1]](MaxPooling1D__B3_L6/ExpandDims)' with input shapes: [?,4,1,16].\n\nCall arguments received by layer \"MaxPooling1D__B3_L6\" (type MaxPooling1D):\n  \u2022 inputs=tf.Tensor(shape=(None, 4, 16), dtype=float32)\n"]
